blog/urls.py
from django.urls import path

from . import views


urlpatterns=[

    path("", views.posts, name="posts"),
    path('<int:id>/', views.post, name="post"),
]

proximahora/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', views.home),
    path('home', views.home, name='home'),
    path('ingresar_plataforma/', views.ingresar_plataforma, name='ingresar_plataforma'),
    path('salir_plataforma/', views.salir_plataforma, name='salir_plataforma'),
    path('administrador/', views.administrador, name='administrador'),
    path('registrado/', views.registrado, name='registrado'),
    path('especialista/', views.especialista, name='especialista'),
    path('about/', views.about, name='about'),
    path('ayuda/', views.ayuda, name='ayuda'),
    path('test/', views.test, name='test'),     
    path('tablas/', include ('tablas.urls')),
    path('usuarios/', include ('usuarios.urls')),
    path('especialistas/', include ('especialistas.urls')),
    path("blog", include('blog.urls')),
    path("banner", include('banner.urls')),
        
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
#
# urls.py usuarios
#
from django.urls import path
from . import views

urlpatterns = [

    path('personas_listar/', views.personas_listar, name='personas_listar'),
    path('personas_password/', views.personas_password, name='personas_password'),
    path('personas_cambiarestado/', views.personas_cambiarestado, name='personas_cambiarestado'),
    path('personas_verificarut/', views.personas_verificarut, name='personas_verificarut'),
    path('personas_verpersona/', views.personas_verpersona.as_view(), name='personas_verpersona'),
    path('validarlogin/', views.validarlogin, name='validarlogin'),
    path('dologin/', views.dologin, name='dologin'), 
    path('confirmacambioclave/', views.confirmacambioclave, name='confirmacambioclave'),  
    path('confirmaolvidoclave/', views.confirmaolvidoclave, name='confirmaolvidoclave'),         
    path('enviarcontacto/', views.enviarcontacto, name='enviarcontacto'),     
    path('registro_inicio/<int:solicita>/', views.registro_inicio, name='registro_inicio'),  
    path('suscripcion_enviar/', views.suscripcion_enviar, name='suscripcion_enviar'),             
    path('suscripcion_final/<int:solicita>/<str:rut>/<str:token>/', views.suscripcion_final, name='suscripcion_final'),      
    path('suscripcion_pagar/', views.suscripcion_pagar, name='suscripcion_pagar'),  
    path('suscripcion_formulario_pago/<str:rut>/<str:token>/', views.suscripcion_formulario_pago, name='suscripcion_formulario_pago'),  
    path('suscripcion_cargar_pago/', views.suscripcion_cargar_pago, name='suscripcion_cargar_pago'),  
    path('registro_usuario_crear/', views.registro_usuario_crear, name='registro_usuario_crear'), 
    path('registros_pendientes/<int:solicita>/', views.registros_pendientes, name='registros_pendientes'),      
    path('cancelaregistro_pendiente/', views.cancelaregistro_pendiente, name='cancelaregistro_pendiente'),      
    path('reenvia_primermail/', views.reenvia_primermail, name='reenvia_primermail'),           
    path('suscripciones_por_aprobar/', views.suscripciones_por_aprobar, name='suscripciones_por_aprobar'),  
    path('suscripciones_cambiar_estado/', views.suscripciones_cambiar_estado, name='suscripciones_cambiar_estado'),               
    path('reenvia_mail_url_pago/', views.reenvia_mail_url_pago, name='reenvia_mail_url_pago'),          
       
       
    ]

usuarios/models.py
#
#   models.py usuarios
#
""" En este modulo se definen los modelos de Usuarios (UsuariosPersonas) y
    Especialistas (UsuariosEspecialistas)  y tablas relacionadas a especialistas
"""
    
    
from django.db import models
from django.contrib.auth.models import User
from tablas.models import *
from proximahora.funciones import uploadfoto_location


class AppsUsuarios:
    ROOT = 0
    ADMINISTRADOR = 1
    ESPECIALISTA = 2
    REGISTRADO = 3
    INVITADO = 4
    RELACIONADO = 5
    APPS_USUARIOS = [
        (ROOT, 'administrador/'),
        (ADMINISTRADOR, 'administrador/'),
        (ESPECIALISTA, 'especialista/'),
        (REGISTRADO, 'registrado/'),
        (INVITADO, 'home/'),
        (RELACIONADO, 'home/'),
        ]
    
class EstadosUsuarios:
    BLOQUEADO = '0'
    HABILITADO = '1'
    ENPROCESO = '2'   # Confirmacion del correo
    ENREVISION = '3'  # revision del admin de datos del especialista
    ESTADOS_USUARIOS = [
        (BLOQUEADO, 'Bloqueado'),
        (HABILITADO, 'Habilitado'),
        (ENPROCESO, 'En Proceso'),
        (ENREVISION, 'En Revision'),
        ]        
    
class PerfilesUsuarios:
    ROOT = '0'
    ADMINISTRADOR = '1'
    ESPECIALISTA = '2'
    REGISTRADO = '3'
    INVITADO = '4'
    RELACIONADO = '5'
    PERFILES_USUARIOS = [
        (ROOT, 'root'),
        (ADMINISTRADOR, 'Administrador'),
        (ESPECIALISTA, 'Especialista'),
        (REGISTRADO, 'Registrado'),
        (INVITADO, 'Invitado'),
        (RELACIONADO, 'Relacionado'),
        ]

class UsuariosPersonas(models.Model):
    '''
    (20.b) Tabla de registro de usuarios del sistema. 
    '''
    rut = models.CharField(max_length=20)
    estado = models.CharField(max_length=1,choices=EstadosUsuarios.ESTADOS_USUARIOS,default=EstadosUsuarios.BLOQUEADO)
    perfil = models.CharField(max_length=1,choices=PerfilesUsuarios.PERFILES_USUARIOS,default=PerfilesUsuarios.REGISTRADO)
    fnacimiento = models.DateField()    
    telefono = models.CharField(max_length=20)  
    cclave = models.PositiveSmallIntegerField(default=1)  
    region = models.ForeignKey(Regiones,on_delete=models.SET_NULL,blank=True,null=True)
    comuna = models.ForeignKey(Comunas,on_delete=models.SET_NULL,blank=True,null=True)
    ciudad = models.ForeignKey(Ciudades,on_delete=models.SET_NULL,blank=True,null=True)
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)

    class Meta:
        db_table = "usuarios_personas"        
        ordering = ['rut','estado','perfil','fnacimiento','telefono','cclave','region','comuna','ciudad','usuario']  


class EstadosSuscripcion:
    BLOQUEADA = '0'
    VIGENTE = '1'
    ESTADOS_SUSCRIPCION = [
        (BLOQUEADA, 'Bloqueada'),
        (VIGENTE, 'Vigente'),
        ]


class EstadosDocumentos:
    PENDIENTE = '0'
    VIGENTE = '1'
    ESTADOS_DOCUMENTOS = [
        (PENDIENTE, 'Pendiente'),
        (VIGENTE, 'Revisados'),
        ]
   
         
class UsuariosEspecialistas(models.Model):
    '''
    (21) Tabla de registro de los especialistas que han contratado servicios de la plataforma y que por medio de ésta ofrecen sus propios servicios
    '''
    foto = models.ImageField(upload_to=uploadfoto_location, blank=True, null=True)
    descripcion = models.CharField(max_length=250,blank=True,null=True)
    estado_suscripcion = models.CharField(max_length=1,choices=EstadosSuscripcion.ESTADOS_SUSCRIPCION,default=EstadosSuscripcion.BLOQUEADA)
    promedio_evaluacion = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    tiempo_consulta = models.PositiveSmallIntegerField(default=0)   
    reg_especialista = models.CharField(max_length=120,blank=True,null=True)
    ctr_altadctos = models.CharField(max_length=1,choices=EstadosDocumentos.ESTADOS_DOCUMENTOS,default=EstadosDocumentos.PENDIENTE)
    categoria = models.ForeignKey(Categorias, on_delete=models.SET_NULL,blank=True,null=True)                
    subcategoria = models.ForeignKey(SubCategorias,on_delete=models.SET_NULL,blank=True,null=True)                
    rubro = models.ForeignKey(Rubros, on_delete=models.SET_NULL,blank=True,null=True)           
    persona = models.OneToOneField(UsuariosPersonas, on_delete=models.CASCADE)
    plan = models.ForeignKey(Planes,on_delete=models.SET_NULL,blank=True,null=True)     
       
    class Meta:
        db_table = "usuarios_especialistas"      
        ordering = ['foto','descripcion','estado_suscripcion','promedio_evaluacion','tiempo_consulta','reg_especialista',
                    'ctr_altadctos','categoria','subcategoria','rubro','persona','plan']                  

         
class UsuariosEvaluacion(models.Model):
    '''
    (22) Tabla de registro de evaluaciones de los especialistas realizadas por los 
    usuarios, toda vez que éstos hayan hecho uso de los servicios del especialista.
    '''  
    fecha = models.DateField()    
    mensaje = models.CharField(max_length=120)
    evaluacion = models.PositiveSmallIntegerField(default=0)                
    usuario = models.ForeignKey(UsuariosPersonas,on_delete=models.CASCADE)
    especialista = models.ForeignKey(UsuariosEspecialistas,on_delete=models.CASCADE)      
         
    class Meta:
        db_table = "usuarios_evaluaciones"       
        ordering = ['fecha','mensaje','evaluacion','usuario','especialista']


class SolicitudEstados:
    RECHAZADA = '0'
    ACEPTADA = '1'
    
class SolicitudRegister:
    USUARIO = '0'
    ESPECIALISTA = '1'
    REVISARPAGO = '2'
    SOLICITUD = [
        (USUARIO, 'Usuario'),
        (ESPECIALISTA, 'Suscriptor'),
        (REVISARPAGO, 'Revisar Pago'),
        ]
   
class UsuariosRegisterRequest(models.Model):
    
    from especialistas.models import EspecialistasPagos
    
    fregistro = models.DateField(auto_now_add=True)   
    rut = models.CharField(max_length=45)
    nombre = models.CharField(max_length=150)
    apellido = models.CharField(max_length=150)
    email = models.CharField(max_length=150)
    telefono = models.CharField(max_length=20)  
    fnacimiento = models.DateField(blank=True,null=True)  
    token = models.CharField(max_length=64)
    solicita = models.CharField(max_length=1,choices=SolicitudRegister.SOLICITUD,default=SolicitudRegister.USUARIO)
    plan = models.BigIntegerField(default=0,blank=True,null=True)
    fpago = models.BigIntegerField(default=0,blank=True,null=True)
    epago = models.ForeignKey(EspecialistasPagos,on_delete=models.SET_NULL,blank=True,null=True)   
        
    class Meta:
        db_table = "usuarios_registros"       
#        ordering = ['fregistro','rut','nombre','apellido','email','telefono','fnacimiento','token','solicita','plan','fpago','epago']
        

usuarios/forms.py
#
#   forms.py usuarios
#
#
from django import forms
from especialistas.models import EspecialistasPagos



# class UploadPagoForm(forms.ModelForm):
#    class Meta:
#        model = EspecialistasPagos
#        fields = ['documento']
        
        

usuarios/templates/especialistas_ajax_list.html
<div id="datatablediv">
    <table id="tablaregs" class="cell-border compact stripe hover order-column" style="width:100%">
        <thead >
            <tr>
                <td width="10%" class="tdtit10">R.U.T.</td>
                <td width="20%" class="tdtit10">Nombre</td>
                <td width="15%" class="tdtit10">Correo</td>                
                <td width="10%" class="tdtit10">Categoría</td>
                <td width="10%" class="tdtit10">SubCategoría</td>
                <td width="10%" class="tdtit10">Revisión<br />Documentos</td>
                <td width="10%" class="tdtit10">Estado<br />Suscripción</td>
                <td width="15%" class="tdtit10">Accion</td>
            </tr>
        </thead>
        <tbody>
            {% for especialista in especialistas %}
            <tr>
                <td class="text8c" id="rutx{{especialista.id}}">
                    <a href='/usuarios/especialistas_detalle?id={{especialista.id}}' class='tip' title='Detalle Especialista'>{{especialista.persona.rut}}</a>
                    <input type="hidden" name="rut{{especialista.id}}" id="rut{{especialista.id}}" value="{{especialista.persona.rut}}" />
                </td>sub
                <td class="text8c" id="nom{{especialista.id}}">{{especialista.persona.usuario.last_name}} , {{especialista.persona.usuario.first_name}} </td>
                <td class="text8c" id="ema{{especialista.id}}">{{especialista.persona.usuario.email}} </td>
                <td class="text8c" id="cat{{especialista.id}}">{{especialista.categoria.nombre}} </td>
                <td class="text8c" id="scat{{especialista.id}}">{{especialista.subcategoria.nombre}} </td>
                <td class="text8c" id="sus{{especialista.id}}">{{especialista.get_ctr_altadctos_display}} </td>
                <td class="text8c" id="rub{{especialista.id}}">{{especialista.get_estado_suscripcion_display}} </td>
                <td class="text8c"> 
                    <button class='btn btn-sm btn-success tip' title='Ver Especialista' onClick='VerRegistro({{especialista.id}})'>
                        <i class='fa fa-search'></i>
                    </button>
                    <button class='btn btn-sm btn-primary tip' title='Editar Especialista' onClick='EditarRegistro({{especialista.id}})'>
                        <i class='fa fa-pencil'></i>
                    </button>
                    {% if especialista.ctr_altadctos == '0' %}
                        <button class='btn btn-sm btn-warning tip' title='Documentos Revisados' onClick='EstadosDocumentos({{especialista.id}})'>
                            <i class="fa fa-check" aria-hidden="true"></i>
                        </button>
                    {% endif %}
                    {% if especialista.estado_suscripcion == '0' %}
                        <button class='btn btn-sm btn-danger tip' title='DesBloquear Suscripción' onClick='DesBloquearRegistro({{especialista.id}})'>
                            <i class='fa fa-unlock aria-hidden="true"'></i>
                        </button>
                    {% else %}
                        <button class='btn btn-sm btn-danger tip' title='Bloquear Suscripción' onClick='BloquearRegistro({{especialista.id}})'>
                            <i class='fa fa-lock'></i>
                        </button>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>   
</div>

usuarios/templates/personas_ajax_list.html
<div id="datatablediv">
    <table id="tablaregs" class="table table-striped table-bordered table-hover" style="width:100%">
        <thead >
            <tr>
                <th width="10%" class="tdtit10">R.U.T.</th>
                <th width="30%" class="tdtit10">Nombre</th>
                <th width="20%" class="tdtit10">Correo</th>                
                <th width="8%" class="tdtit10">Estado<br />Registro</th>
                <th width="7%" class="tdtit10">Perfil</th>
                <th width="10%" class="tdtit10">Estado<br />Sistema</th>
                <th width="15%" class="tdtit10">Accion</th>
            </tr>
        </thead>
        <tbody>
            {% for persona in personas %}
            <tr>
                <td class="text8c" id="rut{{persona.id}}">{{persona.rut}}
                    <input type="hidden" name="id{{persona.id}}" id="id{{persona.id}}" value="{{persona.id}}" />
                    <input type="hidden" name="user{{persona.id}}" id="user{{persona.id}}" value="{{persona.usuario.username}}" />
                </td>
                <td class="text8c" id="nom{{persona.id}}">{{persona.usuario.last_name}} , {{persona.usuario.first_name}} </td>
                <td class="text8c" id="ema{{persona.id}}">{{persona.usuario.email}}</td>
                <td class="text8c" id="est{{persona.id}}">{{persona.get_estado_display}}</td>
                <td class="text8c" id="per{{persona.id}}">{{persona.get_perfil_display}}</td>
                <td class="text8c" id="act{{persona.id}}">
                    {% if persona.usuario.is_active %}
                        Activo
                    {% else %}
                        Bloqueado
                    {% endif %}
                </td>
                <td class="text8c"> 
                    <button class='btn btn-sm btn-success tip' title='Ver Usuario' onClick='VerRegistro({{persona.id}})'>
                        <i class='fa fa-search'></i>
                    </button>
                    <button class='btn btn-sm btn-primary tip' title='Editar Usuario' onClick='EditarRegistro({{persona.id}})'>
                        <i class='fa fa-pencil'></i>
                    </button>
                    <button class='btn btn-sm btn-warning tip' title='Cambiar Password' onClick='CambiarClave({{persona.id}})'>
                        <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
                    </button>
                    {% if persona.usuario.is_active %}
                        <button class='btn btn-sm btn-danger tip' title='Bloquear Usuario' onClick='BloquearRegistro({{persona.id}})'>
                            <i class='fa fa-lock'></i>
                        </button>
                    {% else %}
                        <button class='btn btn-sm btn-danger tip' title='DesBloquear Usuario' onClick='DesBloquearRegistro({{persona.id}})'>
                            <i class='fa fa-unlock aria-hidden="true"'></i>
                        </button>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>   
</div>

usuarios/templates/registro_inicio.html
{% extends 'home_base2.html' %}

{% load static %}

{% block title %}Proxima Hora Registro{% endblock %}

{% block content %}
<!-- datepicker -->
<link rel='stylesheet' type='text/css' href="{% static 'gijgo/core/core.min.css' %}" />
<link rel='stylesheet' type='text/css' href="{% static 'gijgo/datepicker/datepicker.min.css' %}" />
<script type="text/javascript" src="{% static 'gijgo/core/core.min.js' %}"></script>  
<script type="text/javascript" src="{% static 'gijgo/datepicker/datepicker.min.js' %}"></script>  

<!-- Custom JS -->
<script type="text/javascript" src="{% static 'js/usuarios/registro_inicio.js' %}"></script>  

<!-- miga de pan -->
<div class="migapan">
<!-- nombre del menu en que esta -->
  <ul class="breadcrumb">
    <li><a href="/home">Inicio</a></li>
    <li>{{ titulo1 }}</li>
  </ul>
</div>

<div class="row d-flex justify-content-center align-items-center h-100">
  <div class="col col-xl-10">
    <div class="card cajas" > 
      <div class="row g-0">
        <h4 style="text-align: center;">{{ titulo1 }}</h4><hr>

        
<!-- Registro Usuarios y Especialistas Paso 1 -->
        <div class="col-md-6 d-flex align-items-center">
          <div class="card-body p-4 p-lg-5 text-black myform">
            <div class="input-group flex-nowrap mx-4">
              <div id="formcontacto" name="formcontacto" >
                <form name="formsuscripstep1" id="formsuscripstep1" method="post" action="/home"> 
                  {% csrf_token %}
                  <div class="d-flex flex-column">
                    <div class="d-flex flex-column">
                      <label for="formsusrut" class="form-label d-block">R.U.T.
                        <input type="text" class="form-control" id="formsusrut" name="formsusrut" size="20" maxlength="15"  />
                        <input type="hidden" name="formsusrut2" id="formsusrut2" />
                        <input type="hidden" name="formsussolicita" id="formsussolicita" value="{{ solicita }}"/>
                      </label>
                    </div>
                    <div class="d-flex flex-column">
                      <label for="formsusnombre" class="form-label">Nombre(s)
                        <input type="text" class="form-control mt-0 ucword" id="formsusnombre" name="formsusnombre" size="50" maxlength="45" />
                      </label>
                    </div>
                    <div class="d-flex flex-column">
                      <label for="formsusapellido" class="form-label">Apellido(s)
                        <input type="text" class="form-control mt-0 ucword" id="formsusapellido" name="formsusapellido" size="50" maxlength="45" />
                      </label>
                    </div>
                    <div class="d-flex flex-column">
                      <label for="formsusmail" class="form-label d-block">Correo Electrónico 
                        <input type="text" class="form-control mt-0" id="formsusmail" name="formsusmail"  size="50" maxlength="45" />
                      </label> 
                    </div>
                    <div class="d-flex flex-column">
                      <label for="formsusfono" class="form-label d-block">Contacto Telefónico
                        <input type="text" class="form-control mt-0" id="formsusfono" name="formsusfono" size="20" maxlength="20" />
                      </label>
                    </div>
                    <div class="d-flex flex-column">
                      <label for="fnacimiento" class="form-label d-block">Fecha Nacimiento
                        <input type="text"  class="form-control mt-0 fechainput"  id="fnacimiento" name="fnacimiento" size="20"  maxlength="20" />
                      </label>
                    </div>
                    <div class="d-flex align-items-center">
                      <a class="nav-link active mx-3" aria-current="page" href="/media/proximahora/privacidad.pdf"  target="_blank">
                        <input type="checkbox" class="me-2" id="chkacepto" name="chkacepto" />Acepto los Términos y Condiciones </>
                      </a>            
                    </div>
                    <div class="d-flex flex-column">
                      <div id="msgmodal" name="msgmodal">
                        <div id="divmsg" style="display: none;" class="alert alert-warning alert-dismissible fade show text-center" role="alert">
                          <strong><span id="divmsg1"></span></strong>&nbsp;&nbsp;<span id="divmsg2"></span>
                        </div>
                      </div>
                      <div class="pt-1 mb-4 d-flex">
                          <button type="button" data-mdb-button-init data-mdb-ripple-init class="btn boton mx-3" name="btnformsuscrip" id="btnformsuscrip">Enviar</button>
                          <button type="button" data-mdb-button-init data-mdb-ripple-init class="btn boton" name="btncancelar" id="btncancelar">Cancelar</button>   
                      </div>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
<!-- Fin Registro Usuarios y Especialistas Paso 1 -->

        <div class="col-md-6 ">
          <h4>Conoce los beneficios de estar en ProximaHora</h4>
          <div class="beneficios d-flex align-items-right">
           <div class="card  cards-beneficios ">
            <figure>
                <img src="{% static 'img/booking.svg' %}" class="card-img-top " />
            </figure>
            <div class="card-body">
                <h5 class="card-title">Tomar hora</h5>
                Permite acceso a clientes nuevos y recurrentes a servicio de búsqueda, agendamiento y mucho m&aacute;s
                para tomar su pr&oacute;xima hora.
            </div>
        </div>
        <div class="card  cards-beneficios">
            <figure>
                <img src="{% static 'img/doctor.svg' %}" class="card-img-top img-fluid rounded-start" />
            </figure>
            <div class="card-body">
                <h5 class="card-title">Certificaci&oacute;n</h5>
                Profesionales de la Salud en Chile cuentan con registro en Superintendencia de Salud, validados por
                ProximaHora.
            </div>
        </div>
        <div class="card  cards-beneficios"  >
          <figure>
              <img src="{% static 'img/access.svg' %}" class="card-img-top img-fluid rounded-start" />
          </figure>
          <div class="card-body">
              <h5 class="card-title">Acceso</h5>
              Acceso r&aacute;pido 24/7 a búsqueda y agendamiento con su profesional desde cualquier lugar donde se
              encuentre.
          </div>
      </div>
      
        </div>
      </div>
    </div>
  </div>
</div>

<!-- modal de Confirmacion -->
<div class="modal modallogin fade" id="AvisoRegStep1Modal" name="AvisoRegStep1Modal" tabindex="-1" aria-labelledby="ModalLogin" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <div style="max-width: 100%;">
          <div class="container py-2 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
              <div class="col col-xl-10">
                <div class="card" style="border-radius: 0.5rem;">
                  <div class="row g-0">
                    <div class="col d-flex align-items-center">
                      <div class="card-body p-2 p-lg-2 text-black myform">
                        <div class="d-flex align-items-center mb-3 pb-1">
                          <span class="mb-0"><img src="{% static 'img/logoph-01.svg' %}" width="100" /></span>
                        </div>
                        <div class="d-flex justify-content-center">
                          <h4>Solicitud de {{ titulo2 }} a Pr&oacute;xima Hora</h4>
                        </div>
                        <div class="modal-body">
                          <div id="msgcontinuarreg1" name="msgcontinuarreg1">
                            ¿Desea continuar con su {{ titulo2 }} en Pr&oacute;xima Hora?
                            <div></div>
                            <div class="pt-1 mb-4">
                              <button type="button" class="btn btn-secondary" data-dismiss="modal" id="koenviosuscrip" name="koenviosuscrip">Cancelar</button>
                              <button type="button" class="btn btn-primary" id="okenviosuscrip" name="okenviosuscrip">Continuar</button>
                            </div>
                          </div>
                          <div id="msgresreg1" name="msgresreg1">
                            <div id="divregerror" style="display: none;" class="alert alert-warning alert-dismissible fade show text-center" role="alert">
                              <strong><span id="divregerror1"></span></strong>
                            </div>
                            <div class="pt-1 mb-4">
                              <button type="button" class="btn btn-primary" id="oksubmitformsuscrip"  name="oksubmitformsuscrip">Terminar</button>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

usuarios/templates/registros_pendientes_ajax.html
<div id="datatablediv">
    <table id="tablaregs" class="table table-striped table-bordered table-hover" style="width:100%">
        <thead >
            <tr>
                <th width="10%" class="tdtit10">F.Ingreso</th>
                <th width="10%" class="tdtit10">R.U.T.</th>
                <th width="40%" class="tdtit10">Nombre</th>
                <th width="15%" class="tdtit10">Correo</th>                
                <th width="15%" class="tdtit10">Teléfono</th>
                <th width="10%" class="tdtit10">Accion</th>
            </tr>
        </thead>
        <tbody>
            {% for solicitud in solicitudes %}
            <tr>
                <td class="text8c" id="fec{{solicitud.fregistro}}">{{solicitud.fregistro|date:"d-m-Y"}}</td>
                <td class="text8c" id="rut{{solicitud.id}}">{{solicitud.rut}}  </td>
                    <input type="hidden" name="id{{solicitud.id}}" id="id{{solicitud.id}}" value="{{solicitud.id}}" />
                <td class="text8c" id="nom{{solicitud.id}}">{{solicitud.apellido}} , {{solicitud.nombre}} </td>
                <td class="text8c" id="ema{{solicitud.id}}">{{solicitud.email}}</td>
                <td class="text8c" id="fon{{solicitud.id}}">{{solicitud.telefono}}</td>
                <td class="text8c"> 
                    <button class='btn btn-sm btn-primary tip' title='Reenviar Correo' onClick='RenviarMail({{solicitud.id}})'>
                        <i class='fa-solid fa-envelope'></i>
                    </button>
                    <button class='btn btn-sm btn-danger tip' title='Cancelar Registro' onClick='CancelarRegistro({{solicitud.id}})'>
                        <i class='fa-solid fa-trash-can'></i>
                    </button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>   
</div>