blog/urls.py
from django.urls import path

from . import views


urlpatterns=[

    path("", views.posts, name="posts"),
    path('<int:id>/', views.post, name="post"),
]

proximahora/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', views.home),
    path('home', views.home, name='home'),
    path('ingresar_plataforma/', views.ingresar_plataforma, name='ingresar_plataforma'),
    path('salir_plataforma/', views.salir_plataforma, name='salir_plataforma'),
    path('administrador/', views.administrador, name='administrador'),
    path('registrado/', views.registrado, name='registrado'),
    path('especialista/', views.especialista, name='especialista'),
    path('about/', views.about, name='about'),
    path('ayuda/', views.ayuda, name='ayuda'),
    path('test/', views.test, name='test'),     
    path('tablas/', include ('tablas.urls')),
    path('usuarios/', include ('usuarios.urls')),
    path('especialistas/', include ('especialistas.urls')),
    path("blog", include('blog.urls')),
    path("banner", include('banner.urls')),
        
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tablas/urls.py
#
# urls.py tablas
#
from django.urls import path
from . import views

urlpatterns = [

    path('regiones/', views.regiones, name='regiones'),
    path('ciudades/', views.ciudades, name='ciudades'),
    path('selectciudades', views.selectciudades, name='selectciudades'),
    path('comunas/', views.comunas, name='comunas'),
    path('selectcomunas', views.selectcomunas, name='selectcomunas'),
    path('categorias/', views.categorias, name='categorias'),
    path('selectcategorias', views.selectcategorias, name='selectcategorias'),
    path('subcategorias/', views.subcategorias, name='subcategorias'),
    path('selectsubcategorias', views.selectsubcategorias, name='selectsubcategorias'),    
    path('rubros/', views.rubros, name='rubros'),
    path('formapagosalud/', views.formapagosalud, name='formapagosalud'),
    path('formapagogral/', views.formapagogral, name='formapagogral'),
    path('tipoprevision/', views.tipoprevision, name='tipoprevision'),
    path('modalidadatencion/', views.modalidadatencion, name='modalidadatencion'),
    path('promociones/', views.promociones, name='promociones'),
    path('planes/', views.planes, name='planes'),
    path('planes_detalles/', views.planes_detalles, name='planes_detalles'),
]

tablas/models.py
from django.db import models

class Regiones(models.Model):
    '''
    (1) Tabla Normalizada de Regiones
    ''' 
    nombre = models.CharField(max_length=45)
    numero = models.CharField(max_length=4)
    
    class Meta:
        ordering = ['nombre', 'numero']
   
    def __str__(self):
        return (self.nombre)

class Comunas(models.Model):
    '''
    (2) Tabla Normalizada de Comunas
    ''' 
    nombre = models.CharField(max_length=45)
    region = models.ForeignKey(Regiones, on_delete=models.CASCADE)

    class Meta:
        ordering = ['nombre']
        
    def __str__(self):
        return (self.nombre)
    

class Ciudades(models.Model):
    '''
    (3) Tabla Normalizada de Ciudades
    ''' 
    nombre = models.CharField(max_length=45)
    region = models.ForeignKey(Regiones, on_delete=models.CASCADE)

    class Meta:
        ordering = ['nombre']

    def __str__(self):
        return (self.nombre)
    
    
class Rubros(models.Model):
    '''
    (4) Tabla Normalizada de Rubros de Especialistas
    ''' 
    NO = '0'
    SI = '1'
    AREASALUD_CHOICES = [
        (NO, 'No'),
        (SI, 'Si'),
        ]
    nombre = models.CharField(max_length=45)
    areasalud = models.CharField(max_length=1,choices=AREASALUD_CHOICES)
    
    class Meta:
        ordering = ['nombre', 'areasalud']

    def __str__(self):
        return (self.nombre)   
        
class Categorias(models.Model):
    '''
    (5) Tabla Normalizada de Categorias de Especialistas
    ''' 
    nombre = models.CharField(max_length=45)
    rubro = models.ForeignKey(Rubros, on_delete=models.CASCADE)
    
    class Meta:
        ordering = ['nombre']
 
    def __str__(self):
        return (self.nombre)   

        
class SubCategorias(models.Model):
    '''
    (6) Tabla Normalizada de SubCategorias de Especialistas
    '''
    nombre = models.CharField(max_length=45)
    categoria  = models.ForeignKey(Categorias, on_delete=models.CASCADE)
    rubro = models.ForeignKey(Rubros, on_delete=models.CASCADE)
    
    class Meta:
        ordering = ['nombre']

    def __str__(self):
        return (self.nombre)   

 
class FormaPagoSalud(models.Model):
    '''
    (7) Tabla Normalizada de Formas de Pago a Especialistas Area Salud
    '''
    nombre = models.CharField(max_length=45)
        
    class Meta:
        ordering = ['nombre']

    def __str__(self):
        return (self.nombre)   


class FormaPagoGral(models.Model):
    '''
    (8) Tabla Normalizada de Formas de Pago en General y excluye a Especialistas Area Salud
    '''
    nombre = models.CharField(max_length=45)
        
    class Meta:
        ordering = ['nombre']

    def __str__(self):
        return (self.nombre)   

        
class TipoPrevision(models.Model):
    '''
    (9) Tabla Normalizada de Tipos de Prevision
    '''
    nombre = models.CharField(max_length=45)
            
    class Meta:
        ordering = ['nombre']
        

class ModalidadAtencion(models.Model):
    '''
    (10) Tabla Normalizada de Modalidades de Atención
    '''
    nombre = models.CharField(max_length=45)
        
    class Meta:
        ordering = ['nombre']

    def __str__(self):
        return (self.nombre)   


class EstadosPromociones:
    TERMINADA = '0'
    VIGENTE = '1'
    ESTADOS_PROMOCIONES = [
        (TERMINADA, 'Terminada'),
        (VIGENTE, 'Vigente'),
        ]

class Promociones(models.Model):
    '''
    (11) Tabla Normalizada de Promociones
    '''
    nombre = models.CharField(max_length=45)
    fdesde = models.DateField()    
    fhasta = models.DateField()
    pclave = models.CharField(max_length=45)
    dcto_porcentaje = models.DecimalField(max_digits=10, decimal_places=2)
    dcto_cantidad = models.DecimalField(max_digits=10, decimal_places=2)
    estado = models.CharField(max_length=1,choices=EstadosPromociones.ESTADOS_PROMOCIONES,default=EstadosPromociones.VIGENTE)                
                    
    class Meta:
        ordering = ['nombre','fdesde','fhasta','pclave','dcto_porcentaje','dcto_cantidad']
        
    def __str__(self):
        return (self.nombre)   


class EstadosPlanes:
    TERMINADO = '0'
    VIGENTE = '1'
    ESTADOS_PLANES = [
        (TERMINADO, 'Terminado'),
        (VIGENTE, 'Vigente'),
        ]

class PeriodicidadPlanes:
    TRIMESTRAL = 0
    SEMESTRAL = 1
    ANUAL = 2
    PERIODICIDAD_PLANES = [
        (TRIMESTRAL, 'Trimestral'),
        (SEMESTRAL, 'Semestral'),
        (ANUAL, 'Anual'),
        ]
    MESES_PLANES = [
        (TRIMESTRAL, 3),
        (SEMESTRAL, 6),
        (ANUAL, 12),
        ]

class Planes(models.Model):
    '''
    (16) Tabla de registro planes ofrecidos a especialistas.
    '''  
    fdesde = models.DateField()
    fhasta = models.DateField()    
    nombre = models.CharField(max_length=45)
    estado = models.CharField(max_length=1,choices=EstadosPlanes.ESTADOS_PLANES)                
    periodicidad = models.CharField(max_length=1,choices=PeriodicidadPlanes.PERIODICIDAD_PLANES)
    valor = models.DecimalField(max_digits=8, decimal_places=2,blank=True,null=True)           
             
    class Meta:
        db_table = "tablas_planes"       
        ordering = ['fdesde','fhasta','nombre','estado','periodicidad','valor']
        
        

tablas/views.py
#
#   views.py tablas
#
""" Este modulo premite realizar operaciones CRUD de Regiones, Comunas, Ciudades, Rubros, Categorias, Subcategorias,Formas de Pagos Area Salud
    Formas de Pagos Otros Rubros, Tipo de Prevision, Modalidad de Atencion y Promociones
    Metodo GET muestra los registros en DB via ajax
    Metodo POST recibe por ajax el CRUD a realizar y los campos a modificar
    accion=0 Elimina registro
    accion=1 Crea registro
    accion=2 modifica registro """

from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from proximahora.funciones import *
from .models import *


# @csrf_exempt
# @login_required(login_url='/users/userlogin')
def regiones(request):
    regiones = Regiones.objects.all()
    if (request.method == 'GET'):
        return render(request, 'regiones/regiones_list.html', {'regiones': regiones})
    else:
        accion = request.POST.get('accion')
        id = request.POST.get('id')
        numero = request.POST.get('numero')
        nombre = request.POST.get('nombre')
        if (accion == FuncionesAjax.ELIMINAR):
            try:
                Regiones.objects.filter(id=id).delete()
            except Exception as e:
                print('Accion= ' + accion + ' Error= '+str(e))
        elif (accion == FuncionesAjax.CREAR):
            try:
                Regiones.objects.create(nombre=nombre, numero=numero)
            except Exception as e:
                print('Accion= ' + accion + ' Error= '+str(e))
        else:
            try:
                Regiones.objects.filter(id=id).update(numero=numero, nombre=nombre)
            except Exception as e:
                print('Accion= ' + accion + ' Error= '+str(e))
        return render(request, 'regiones/regiones_ajax_list.html', {'regiones': regiones})


#  @login_required(login_url='/users/userlogin')
def ciudades(request):
    ciudades = Ciudades.objects.all()
    if (request.method == 'GET'):
        regiones = Regiones.objects.order_by('nombre')
        return render(request, 'ciudades/ciudades_list.html', {'ciudades': ciudades, 'regiones': regiones})
    else:
        accion = request.POST.get('accion')
        id = request.POST.get('id')
        nombre = request.POST.get('nombre')
        region = request.POST.get('region')
        if (accion == FuncionesAjax.ELIMINAR):
            try:
                Ciudades.objects.filter(id=id).delete()
            except Exception as e:
                print('Accion= ' + accion + ' Error= '+str(e))
        elif (accion == FuncionesAjax.CREAR):
            try:
                Ciudades.objects.create(nombre=nombre, region_id=region)
            except Exception as e:
                print('Accion= ' + accion + ' Error= '+str(e))
        else:
            try:
                Ciudades.objects.filter(id=id).update(
                    nombre=nombre, region_id=region)
            except Exception as e:
                print('Accion= ' + accion + ' Error= '+str(e))
        return render(request, 'ciudades/ciudades_ajax_list.html', {'ciudades': ciudades})


def selectciudades(request):
    if (request.method == 'GET'):
        region = request.GET.get('region')
        ciudad = request.GET.get('ciudad')
        estilo = request.POST.get('estilo')
        if (region == 0):
            ciudades = Ciudades.objects.order_by('nombre')
        else:        
            ciudades = Ciudades.objects.filter(region_id=region).order_by('nombre')
        if (estilo is None):
            return render(request,'ciudades/ciudades_ajax_select_adm.html', {'ciudades': ciudades, 'miciudad': ciudad})
        else:
            return render(request,'ciudades/ciudades_ajax_select_user.html', {'ciudades': ciudades, 'miciudad': ciudad})
    else:
        return render(request, 'error.html', {'error_ph': ErroresPH.ERRORESPH[ErroresPH.ERROR_ACCESO][1]})
     
        
# @login_required(login_url='/users/userlogin')
def comunas(request):
    comunas = Comunas.objects.all()
    if (request.method == 'GET'):
        regiones = Regiones.objects.order_by('nombre')
        return render(request, 'comunas/comunas_list.html', {'comunas': comunas, 'regiones': regiones})
    else:
        accion = request.POST.get('accion')
        id = request.POST.get('id')
        nombre = request.POST.get('nombre')
        region = request.POST.get('region')
        if (accion == FuncionesAjax.ELIMINAR):
            try:
                Comunas.objects.filter(id=id).delete()
            except Exception as e:
                print('Accion= ' + accion + ' Error= '+str(e))
        elif (accion == FuncionesAjax.CREAR):
            try:
                Comunas.objects.create(nombre=nombre, region_id=region)
            except Exception as e:
                print('Accion= ' + accion + ' Error= '+str(e))
        else:
            try:
                Comunas.objects.filter(id=id).update(nombre=nombre, region_id=region)
            except Exception as e:
                print('Accion= ' + accion + ' Error= '+str(e))
        return render(request, 'comunas/comunas_ajax_list.html', {'comunas': comunas})

    
def selectcomunas(request):
    if (request.method == 'GET'):
        region = request.GET.get('region')
        comuna = request.GET.get('comuna')
        estilo = request.POST.get('estilo')
        if (region == 0):
            comunas = Comunas.objects.order_by('nombre')
        else:        
            comunas = Comunas.objects.filter(region_id=region).order_by('nombre')
        if ((estilo is None) or (estilo == 0)):
            return render(request,'comunas/comunas_ajax_select_adm.html', {'comunas': comunas, 'micomuna': comuna})
        else:
            return render(request,'comunas/comunas_ajax_select_user.html', {'comunas': comunas, 'micomuna': comuna})
    else:
        return render(request, 'error.html', {'error_ph': ErroresPH.ERRORESPH[ErroresPH.ERROR_ACCESO][1]})


# @login_required(login_url='/users/userlogin')
def categorias(request):
    categorias = Categorias.objects.all()
    if (request.method == 'GET'):
        rubros = Rubros.objects.order_by('nombre')
        return render(request, 'varios/categorias_list.html', {'categorias': categorias, 'rubros': rubros})
    else:
        accion = request.POST.get('accion')
        id = request.POST.get('id')
        nombre = request.POST.get('nombre')
        rubro = request.POST.get('rubro')
        if (accion == FuncionesAjax.ELIMINAR):
            try:
                Categorias.objects.filter(id=id).delete()
            except Exception as e:
                print('Accion= ' + accion + ' Error= '+str(e))
        elif (accion == FuncionesAjax.CREAR):
            try:
                Categorias.objects.create(nombre=nombre, rubro_id=rubro)
            except Exception as e:
                print('Accion= ' + accion + ' Error= '+str(e))
        else:
            try:
                Categorias.objects.filter(id=id).update(nombre=nombre, rubro_id=rubro)
            except Exception as e:
                print('Accion= ' + accion + ' Error= '+str(e))
        return render(request, 'varios/categorias_ajax_list.html', {'categorias': categorias})


    
def selectcategorias(request):
    if (request.method == 'POST'):
        rubro = request.POST.get('rubro')  
        estilo = request.POST.get('estilo')
    else:
        rubro = request.POST.get('rubro') 
        estilo = request.GET.get('estilo')                  
    categorias = Categorias.objects.filter(rubro_id=rubro).order_by('nombre')
    if ((estilo is None) or (estilo == 0)):
        return render(request,'varios/categorias_ajax_select_adm.html', {'categorias': categorias})
    else:
       return render(request,'varios/categorias_ajax_select_user.html', {'categorias': categorias})
    
    
# @login_required(login_url='/users/userlogin')
def subcategorias(request):
    if (request.method == 'GET'):
        subcategorias = SubCategorias.objects.all()
        categorias = Categorias.objects.order_by('nombre')
        return render(request, 'varios/subcategorias_list.html', {'subcategorias': subcategorias, 'categorias': categorias})
    else:
        accion = request.POST.get('accion')
        id = request.POST.get('id')
        nombre = request.POST.get('nombre')
        categoria_id = int(request.POST.get('categoria'))
        if (accion == FuncionesAjax.ELIMINAR):
            try:
                SubCategorias.objects.filter(id=id).delete()
            except Exception as e:
                print('Accion= ' + accion + ' Error= '+str(e))
        else:
            try:
                rubro_id = Categorias.objects.get(pk=categoria_id).rubro.id
            except Exception as e:
                 print('Accion= ' + accion + ' Error= '+str(e))
            if (accion == FuncionesAjax.CREAR):
                try:
                    SubCategorias.objects.create(nombre=nombre, categoria_id=categoria_id, rubro_id=rubro_id)
                except Exception as e:
                    print('Accion= ' + accion +' Error= '+str(e))
            else:
                try:
                    SubCategorias.objects.filter(id=id).update(nombre=nombre, categoria_id=categoria_id, rubro_id=rubro_id)
                except Exception as e:
                    print('Accion= ' + accion + ' Error= '+str(e))
        subcategorias = SubCategorias.objects.all()
        return render(request, 'varios/subcategorias_ajax_list.html', {'subcategorias': subcategorias})
    
    
def selectsubcategorias(request):
    if (request.method == 'POST'):
        categoria = request.POST.get('categoria')
        estilo = request.POST.get('estilo')
    else:
        categoria = request.GET.get('categoria')
        estilo = request.GET.get('estilo')
    subcategorias = SubCategorias.objects.filter(categoria_id=categoria).order_by('nombre')
    if ((estilo is None) or (estilo == 0)):

tablas/templates/varios/categorias_ajax_select_adm.html
<select required="required" class="form-select w-auto" name="categoria" id="categoria" style="font-size:11px;">
    {% for categoria in categorias %}    
        {% if categoria.id == micategoria %} 
            <option value="{{categoria.id}}" selected class="text8l">{{categoria.nombre}}</option>
        {% else %}
            <option value="{{categoria.id}}" class="text8l">{{categoria.nombre}}</option>
        {% endif %}
    {% endfor %}
</select>

tablas/templates/varios/categorias_list.html
{% extends 'home_adm_base.html' %}

{% load static %}

{% block title %}ProximaHora Categorias {% endblock %}

{% block content %}

    <!-- Custom JS -->
    <script type="text/javascript" src="{% static 'js/tablas/categorias.js' %}"></script>  

    <div class="container-xxl mt-4">
    
        {% csrf_token %}
    
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <div class="table-responsive">
                    <table style="width:100%">
                        <tr>
                            <td width="90%" class="titform20">Especialidades</td>
                            <td width="10%" class="text8c">
                                <button class='btn btn-sm btn-primary tip' title='Agregar Categoria' onClick='AgregarRegistro()' >
                                    <i class='fa-solid fa-plus'></i>
                                </button>                        
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    
        {% include 'varios/categorias_ajax_list.html' %}
    
    </div>

    <div id="diagedit">
        <div class="container-fluid py-3">
            <div class="row">
                <div class="col-lg-12">            
                    <div class="row">
                        <div class="col-lg-12 mx-auto">
                            <div class="card border-secondary">
                                <div class="card-body">
                                    <div class="form-group">
                                        <label class="tit10lb">Identificador</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fa fa-key"></i></span>
                                            </div>
                                            <input type="text"  name="id" id="id" size="10" class="text8r readonly"/>
                                        </div>
                                        <div id="strengthMessage"></div>
                                    </div> 
                                    <div class="form-group">
                                        <label class="tit10lb">Nombre Especialidad</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fa fa-address-card"></i></span>
                                            </div>
                                            <input type="text" name="nombre" id="nombre" placeholder="Nombre" size="50" maxlength="45" class="form-control ucword w-50 text8l  " />
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="tit10lb">Rubro</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fa fa-bars"></i></span>
                                            </div>
                                            <select required="required" class="form-control w-auto" name="rubro" id="rubro" style="font-size:12px;">
                                                {% for rubro in rubros %}
                                                    <option value="{{ rubro.id }}" class="text8l">{{ rubro.nombre }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
{% endblock %}

tablas/templates/varios/planes_ajax_list.html
{% load humanize %}
{% load i18n %}
{% load l10n %}

<div id="datatablediv">
    <table id="tablaregs" class="table table-striped table-bordered table-hover" style="width:100%">
        <thead >
            <tr>
                <th width="10%" class="tdtit10">ID</th>
                <th width="30%" class="tdtit10">Nombre</th>
                <th width="10%" class="tdtit10">F.Inicio</th>
                <th width="10%" class="tdtit10">F.Término</th>
                <th width="10%" class="tdtit10">Periodicidad</th>                
                <th width="10%" class="tdtit10">Valor</th>
                <th width="10%" class="tdtit10">Estado</th>
                <th width="10%" class="tdtit10">Acción</th>
            </tr>
        </thead>
        <tbody>
            {% for plan in planes %}
            <tr>
                <td class="text8c" id="id{{plan.id}}">{{plan.id|stringformat:"s"}}</td>
                <td class="text8c" id="nom{{plan.id}}">{{plan.nombre}}</td>
                <td class="text8c" id="fin{{plan.id}}">{{plan.fdesde|date:"d-m-Y"}}</td>
                <td class="text8c" id="fte{{plan.id}}">{{plan.fhasta|date:"d-m-Y"}}</td>
                <td class="text8c" id="per{{plan.id}}">{{plan.get_periodicidad_display}}
                    <input type="hidden" name="perid{{plan.id}}" id="perid{{plan.id}}" value="{{plan.periodicidad}}" />
                </td>
                <td class="text8c" id="val{{plan.id}}">{{plan.valor|floatformat:2|intcomma}}</td>
                <td class="text8c" id="est{{plan.id}}">{{plan.get_estado_display}}
                    <input type="hidden" name="estid{{plan.id}}" id="estid{{plan.id}}" value="{{plan.estado}}" />
                </td>
                <td class="text8c"> 
                    <button class='btn btn-sm btn-primary tip' title='Editar Plan' onClick='EditarRegistro({{plan.id}})'>
                        <i class='fa-solid fa-pencil'></i>
                    </button>
                    <button class='btn btn-sm btn-danger tip' title='Eliminar Plan' onClick='BorrarRegistro({{plan.id}})'>
                        <i class='fa-solid fa-trash-can'></i>
                    </button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>   
</div>

tablas/templates/varios/promociones_ajax_list.html
{% load humanize %}
{% load i18n %}
{% load l10n %}

<div id="datatablediv">
    <table id="tablaregs" class="table table-striped table-bordered table-hover" style="width:100%">
        <thead >
            <tr>
                <th width="10%" class="tdtit10">ID</th>
                <th width="25%" class="tdtit10">Nombre</th>
                <th width="10%" class="tdtit10">F.Inicio</th>
                <th width="10%" class="tdtit10">F.Término</th>
                <th width="10%" class="tdtit10">P.Clave</th>                
                <th width="10%" class="tdtit10">Dcto. %</th>
                <th width="10%" class="tdtit10">Dcto. Valor</th>
                <th width="10%" class="tdtit10">Estado</th>
                <th width="10%" class="tdtit10">Acción</th>
            </tr>
        </thead>
        <tbody>
            {% for promocion in promociones %}
            <tr>
                <td class="text8c" id="id{{promocion.id}}">{{promocion.id|stringformat:"s"}}</td>
                <td class="text8c" id="nom{{promocion.id}}">{{promocion.nombre}}</td>
                <td class="text8c" id="fin{{promocion.id}}">{{promocion.fdesde|date:"d-m-Y"}}</td>
                <td class="text8c" id="fte{{promocion.id}}">{{promocion.fhasta|date:"d-m-Y"}}</td>
                <td class="text8c" id="pcl{{promocion.id}}">{{promocion.pclave}}</td>
                <td class="text8c" id="dc1{{promocion.id}}">{{promocion.dcto_porcentaje|floatformat:2|intcomma}}</td>
                <td class="text8c" id="dc2{{promocion.id}}">{{promocion.dcto_cantidad|floatformat:"0u"|intcomma}}</td>
                <td class="text8c" id="est{{promocion.id}}">{{promocion.get_estado_display}}
                    <input type="hidden" name="estid{{promocion.id}}" id="estid{{promocion.id}}" value="{{promocion.estado}}" />
                </td>
                <td class="text8c"> 
                    <button class='btn btn-sm btn-primary tip' title='Editar Promoción' onClick='EditarRegistro({{promocion.id}})'>
                        <i class='fa-solid fa-pencil'></i>
                    </button>
                    <button class='btn btn-sm btn-danger tip' title='Eliminar Promoción' onClick='BorrarRegistro({{promocion.id}})'>
                        <i class='fa-solid fa-trash-can'></i>
                    </button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>   
</div>

tablas/templates/varios/rubros_ajax_list.html
<div id="datatablediv" >
    <table id="tablaregs" class="table table-striped table-bordered table-hover" style="width:100%">
        <thead >
            <tr>
                <th width="10%" class="tdtit10">ID</th>
                <th width="60%" class="tdtit10">Rubro</th>
                <th width="20%" class="tdtit10">Area Salud</th>
                <th width="10%" class="tdtit10">Acción</th>
            </tr>
        </thead>
        <tbody>
            {% for rubro in rubros %}
            <tr>
                <td class="text8c" id="id{{rubro.id}}">{{rubro.id|stringformat:"s"}}</td>
                <td class="text8c" id="nom{{rubro.id}}">{{rubro.nombre}}</td>
                <td class="text8c" id="asa{{rubro.id}}">{{rubro.get_areasalud_display}}
                    <input type="hidden"  name="asalud{{rubro.id}}" id="asalud{{rubro.id}}" value="{{rubro.areasalud}}" />
                </td>
                <td class="text8c"> 
                    <button class='btn btn-sm btn-primary tip' title='Editar Rubro' onClick='EditarRegistro({{rubro.id}})'>
                        <i class='fa-solid fa-pencil'></i>
                    </button>
                    <button class='btn btn-sm btn-danger tip' title='Eliminar Rubro' onClick='BorrarRegistro({{rubro.id}})'>
                        <i class='fa-solid fa-trash-can'></i>
                    </button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>   
</div>

tablas/templates/varios/subcategorias_ajax_select_user.html
<select required="required" class="form-select w-auto" name="subcategoria" id="subcategoria">
    <option value="0">Seleccione SubEspecialidad</option>
    {% for subcategoria in subcategorias %}    
        {% if subcategoria.id == misubcategoria %} 
            <option value="{{subcategoria.id}}" selected >{{subcategoria.nombre}}</option>
        {% else %}
            <option value="{{subcategoria.id}}">{{subcategoria.nombre}}</option>
        {% endif %}
    {% endfor %}
</select>